# Generated by Django 6.0.4 on 2026-04-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('full_name', models.CharField(max_length=150)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('entry_time', models.TimeField()),
                ('exit_time', models.TimeField()),
                ('present', models.BooleanField(default=False)),
                ('observations', models.TextField(blank=True)),
            ],
        ),
    ]
